### Login
# @name login
POST http://localhost:4040/login
Content-Type: application/json

{
  "username": "admin-1",
  "password": "passAdmin1"
}

### Capture the token after the login request completes
@token = {{login.response.body.accessToken}}

### Select Company
# This request will automatically send any cookies set in the login response
POST http://localhost:4040/select-company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "companyId": "company-1",
  "userId": "11"
}

### Get current user (/me)
# Requires the session cookie; when `rest-client.rememberCookiesForSubsequentRequests` is true this will be sent automatically
GET http://localhost:4040/session/me
Authorization: Bearer {{token}}
Content-Type: application/json

### Get only admin (/adminOnly)
# Requires the session cookie; when `rest-client.rememberCookiesForSubsequentRequests` is true this will be sent automatically
GET http://localhost:4040/session/adminOnly
Authorization: Bearer {{token}}
Content-Type: application/json

### Logout
# Logs out the current session
DELETE  http://localhost:4040/session/logout
Authorization: Bearer {{token}}
Content-Type: application/json 